### ISSUE TITLE
Data Simulation

### ISSUE THREAD

**Issue by caiodadauto** [cervejaria-ambev/safety#3]
Dear all,

I am interesting about this project; for a better understanding of the application environment, I would like to know how the data was simulated for generate the file `data.csv`? More specifically, what are the distributions that was used for each feature? Or what is the methodology to create the simulation?

Moreover, I saw that the creation of a description for the data is a future work, but there is a raw file with the description for each feature (it can be in Portuguese)? 

Thanks.

**Comment by ksenhuck** [comment]
Hey @caiodadauto, 

First of all, thank you for getting envolved !

A few parts of the data were just anonymized and others we tested intenally and then changed without a methodology.

There isn't the description for each feature yet. But we are going to add this part until the end of this week.

If you have any more question, I am more than glad to help as much as possible !

**Comment by caiodadauto** [comment]
Okay @ksenhuck, I get it.

Thanks!
